version: "3.7"
services:
  webapp:
    image: tianyawy/spring-health-check:1.0
    deploy:
      replicas: 3
      update_config:
        order: start-first
        delay: 300s
        parallelism: 2
      restart_policy:
        delay: 5s
        max_attempts: 3
        window: 120s
      rollback_config:
        order: start-first
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost"]
        start-period: 20s
    ports:
      - "80:8080"


