version: "3.7"
services:
  webapp:
    image: tianyawy/spring-health-check:#tag#
    volumes:
      - ~/log:/var/log/
    deploy:
      placement:
        preferences:
          - spread: node.labels.zone
      replicas: 3
      update_config:
        order: start-first
        delay: 300s
        parallelism: 2
      restart_policy:
        delay: 5s
        max_attempts: 3
        window: 120s
      rollback_config:
        order: start-first
    ports:
      - "8082:8080"
    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost:8080/route || exit 1
      start_period: 40s
#      start_period: 20s


