scrape_configs:
  - job_name: 'swarm-service'
    scrape_interval: 30s
    metrics_path: /actuator/prometheus
    dns_sd_configs:
      - names:
          - tasks.deploy-test_webapp
        type: A
        port: 8080
    relabel_configs:
      - source_labels: ['__meta_dns_name']
        target_label: 'service'